joint_tooltip:
  ID: 1
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 0
  CW_Compliance_Slope: 62
  CCW_Compliance_Slope: 62
  Moving_Speed: 0
  Goal_Position: 0

wrist_y_rot:
  ID: 2
  Return_Delay_Time: 0
  CW_Angle_Limit: 180
  CCW_Angle_Limit: 836
  CW_Compliance_Slope: 254
  CCW_Compliance_Slope: 254
  Moving_Speed: 120
  Goal_Position: 836

elbow_y_rot:
  ID: 3
  Return_Delay_Time: 0
  CW_Angle_Limit: 180
  CCW_Angle_Limit: 835
  CW_Compliance_Slope: 254
  CCW_Compliance_Slope: 254
  Moving_Speed: 120
  Goal_Position: 742

base_y_rot:
  ID: 4
  Return_Delay_Time: 0
  CW_Angle_Limit: 320
  CCW_Angle_Limit: 800
  CW_Compliance_Slope: 254
  CCW_Compliance_Slope: 254
  Moving_Speed: 80
  Goal_Position: 324

base_z_rot:
  ID: 5
  Return_Delay_Time: 0
  CW_Angle_Limit: 70
  CCW_Angle_Limit: 700
  CW_Compliance_Slope: 254
  CCW_Compliance_Slope: 254
  Moving_Speed: 80
  Goal_Position: 386