controller_list:
  - name: fake_bartender_arm_controller
    type: $(arg execution_type)
    joints:
      - base_z_rot
      - base_y_rot
      - elbow_y_rot
      - wrist_y_rot
      - gripper_z_rot
  - name: fake_gripper_controller
    type: $(arg execution_type)
    joints:
      - gripper_z_rot
initial:  # Define initial robot poses.
#  - group: bartender_arm
#    pose: home

  []